In [1]:
import pandas as pd
import numpy as np

# Question 1

In [2]:
pd.__version__

'2.3.1'

In [3]:
data = 'https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv'

In [4]:
!wget $data -O data-week-1.csv 

--2025-09-17 06:08:04--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.108.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 874188 (854K) [text/plain]
Saving to: ‘data-week-1.csv’

data-week-1.csv     100%[===================>] 853.70K  --.-KB/s    in 0.04s   

2025-09-17 06:08:04 (23.0 MB/s) - ‘data-week-1.csv’ saved [874188/874188]



In [5]:
df = pd.read_csv('data-week-1.csv')

In [6]:
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

# Question 2

In [7]:
df.shape[0]

9704

# Question 3

In [8]:
df['fuel_type'].nunique()

2

# Question 4

In [9]:
df.isnull().sum().sort_values(ascending=False)

acceleration           930
horsepower             708
num_doors              502
num_cylinders          482
engine_displacement      0
model_year               0
vehicle_weight           0
origin                   0
fuel_type                0
drivetrain               0
fuel_efficiency_mpg      0
dtype: int64

# Question 5

In [10]:
df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max().round(2)

np.float64(23.76)

# Question 6

In [11]:
df['horsepower'].median()

np.float64(149.0)

In [12]:
df['horsepower'].mode()

0    152.0
Name: horsepower, dtype: float64

In [13]:
mode_horsepower = df['horsepower'].mode()[0]
mode_horsepower

np.float64(152.0)

In [14]:
df['horsepower'] = df['horsepower'].fillna(mode_horsepower)

In [15]:
df['horsepower'].median()

np.float64(152.0)

# Question 7

In [16]:
X = df[df['origin'] == 'Asia'][['vehicle_weight', 'model_year']][:7].values

In [17]:
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [18]:
XTX = X.T.dot(X)

In [19]:
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [20]:
XTX_inv = np.linalg.inv(XTX)

In [21]:
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [22]:
y = [1100, 1300, 800, 900, 1000, 1100, 1200]

In [23]:
w = XTX_inv.dot(X.T).dot(y)

In [24]:
w.sum()

np.float64(0.5187709081074016)